name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive


      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Dependencies 📦
        run: npm install

      - name: Generate Static Files 🏗️
        run: npx hexo generate
        env:
          NODE_ENV: production 

      - name: Deploy to GitHub Pages 🚀
        run: |
          git config --global user.name "Mocacy42"
          git config --global user.email "2735749050@qq.com"
          npx hexo deploy